[package]
name = "DeSS"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_extras = "0.31.1"
env_logger = "0.11.7"
reqwest = "0.12.15"
serde = "1.0.219"
tokio = "1.44.1"

