[package]
name = "DeSS"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = "1.44.1"
chacha20poly1305 = { version = "0.10", features = ["rand_core"] }
aead = "0.5"
rand = "0.8"
fs2 = "0.4.3"
sled = "0.34"

[lib]
path = "src/lib.rs"
